services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: ihqe_clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

volumes:
  clickhouse_data:
